config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/houses', to: 'houses#index', as: :houses
  get '/houses/:id', to: 'houses#show', as: :house
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :house
end

app/models/house.rb
class House < ApplicationRecord
  has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/houses/index.html.erb
<div class="l-container" id="houses">
  <% @houses.each do |house| %>
    <div class="b-game-card">
      <div class="b-game-card__cover">
        <%= image_tag house.image_url, alt: "alttext", class: "image-house" %>
      </div>
      <%= link_to "", house_path(house), class: 'card-link' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game Of Thrones Characters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <div class="banner" style="background-image: url(https://www.wallpaperup.com/uploads/wallpapers/2013/12/23/203145/3f50339c45ec14d14d9fdac691f1698f.jpg);">
    </div>
    <div class="navigation">
      <a href="#houses">
        <i class="fas fa-chevron-down"></i>
      </a>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>